apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  # +required Name of the component that this configuration belongs to.
  name: cart-service
  # +required Project name of the component that this component belongs to. Cannot be changed after creation.
  projectName: pet-store
  annotations:
    componentType: service
spec:
  # +optional Incoming connection details for the component (AKA Endpoints).
  inbound:
    # +required Unique name for the endpoint. (This name will be used when generating the managed API)
  - name: cart
    port: 9090
    type: REST
    # +optional Network level visibility of this endpoint. Defaults to Project
    # Accepted values: Project|Organization|Public.
    visibility: Organization
    # +optional Context (base path) of the API that exposed via this endpoint.
    # This is mandatory if the endpoint type is set to REST or GraphQL.
    context: /
  outbound:
    # +optional Defines the service references from the internal API marketplace.
    serviceReferences:
      # +required Name of the service reference.
    - name: choreo://Pet Store 1024/checkout/v1.0/checkout/public
      # +required Name of the dependent configuration instance.
      dependentConfig: config-1
      # +required metadata field to store connection type
      connectionType: service
      # +optional Environment variables to be injected to the component from the dependent configuration.
      env:
        # +required Key name of the dependent configuration.
      - from: service.url
        # +required Environment variable name.
        to: SERVICE_1_URL
      - from: client.id
        to: SERVICE_1_CLIENT_ID
      - from: client.secret
        to: SERVICE_1_CLIENT_SECRET
      - from: token.url
        to: AUTH_TOKEN_URL

